import d1Demo from '../../demos/d1';
import { d1LabResponse } from '../../api/d1-lab';
import { recordsResponse, resetRecordSandboxResponse } from '../../api/records';
import { renderD1Demo } from '../../demos/d1-page';
import {
  D1_RELATIONAL_STORAGE,
  definePlatformLaboratoryCapability,
  noRequestBody,
} from '../route-capability';

const tests = [
  'tests/platform-laboratory-routing.test.ts',
  'tests/d1-lab.test.ts',
  'tests/api-records.test.ts',
  'tests/router.test.ts',
] as const;

const docs = ['docs/ROUTES.md', 'docs/ROUTE-REGISTRY.md'] as const;

export const d1LaboratoryCapability = definePlatformLaboratoryCapability({
  id: 'platform.d1',
  routes: [
    {
      id: 'platform.d1.page',
      pattern: d1Demo.route,
      methods: ['GET'],
      kind: 'page',
      handler: (_request, env) => renderD1Demo(env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'allow' },
      documentation: { title: d1Demo.title, description: d1Demo.summary, docs },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('The D1 laboratory page accepts GET without a request body.'),
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.users',
      pattern: '/__api/d1/users',
      methods: ['GET', 'POST'],
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'users'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 users laboratory API',
        description: 'Lists and creates visitor-scoped relational users in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['POST accepts JSON up to the shared readJson limit; GET consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.user',
      pattern: '/__api/d1/users/:id',
      methods: ['PATCH', 'DELETE'],
      kind: 'api',
      handler: (request, env, params) => d1LabResponse(request, env, 'users', encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['PATCH', 'DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 user item laboratory API',
        description: 'Updates or deletes one visitor-scoped relational user in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['PATCH accepts JSON up to the shared readJson limit; DELETE consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.tasks',
      pattern: '/__api/d1/tasks',
      methods: ['GET', 'POST'],
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'tasks'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 tasks laboratory API',
        description: 'Lists and creates visitor-scoped relational tasks in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['POST accepts JSON up to the shared readJson limit; GET consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.task',
      pattern: '/__api/d1/tasks/:id',
      methods: ['PATCH', 'DELETE'],
      kind: 'api',
      handler: (request, env, params) => d1LabResponse(request, env, 'tasks', encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['PATCH', 'DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 task item laboratory API',
        description: 'Updates or deletes one visitor-scoped relational task in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['PATCH accepts JSON up to the shared readJson limit; DELETE consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.reset',
      pattern: '/__api/d1/reset',
      methods: ['POST'],
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'reset'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 users and tasks reset API',
        description: 'Resets the visitor-scoped D1 users and tasks sandbox to deterministic seed rows.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the scoped sandbox without consuming a request body.'),
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.records',
      pattern: '/v1/demo-records',
      methods: ['GET', 'POST'],
      kind: 'api',
      handler: (request, env) => recordsResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write POST' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 records collection API',
        description: 'Lists readable records or creates an authorized record in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['POST accepts JSON; record values are serialized to at most 4096 bytes.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.record',
      pattern: '/v1/demo-records/:key',
      methods: ['GET', 'PUT', 'DELETE'],
      kind: 'api',
      handler: (request, env, params) => recordsResponse(request, env, encodeURIComponent(params.key)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write PUT/DELETE' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 record item API',
        description: 'Reads, replaces, or deletes one authorized record in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['PUT accepts JSON; GET and DELETE consume no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.records-reset',
      pattern: '/__api/api-sandbox/reset',
      methods: ['POST'],
      kind: 'api',
      handler: (request, env) => resetRecordSandboxResponse(request, env),
      authentication: { mode: 'required', provider: 'demo-access-token-or-operator-bearer' },
      authorization: { mode: 'policy', policy: 'demo:write visitor sandbox' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 record sandbox reset API',
        description: 'Deletes the authenticated visitor sandbox records from D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the authorized record namespace without consuming a request body.'),
      storage: D1_RELATIONAL_STORAGE,
    },
  ],
});
