import { d1LabResponse } from '../../api/d1-lab';
import { recordsResponse, resetRecordSandboxResponse } from '../../api/records';
import { restDemoResponse } from '../../api/rest-demo';
import {
  D1_RELATIONAL_STORAGE,
  definePlatformLaboratoryCapability,
  noRequestBody,
} from '../route-capability';

const tests = [
  'tests/platform-laboratory-routing.test.ts',
  'tests/d1-lab.test.ts',
  'tests/api-records.test.ts',
  'tests/router.test.ts',
] as const;

const docs = ['docs/ROUTES.md', 'docs/ROUTE-REGISTRY.md'] as const;

export const d1LaboratoryCapability = definePlatformLaboratoryCapability({
  id: 'platform.d1',
  routes: [

    {
      id: 'platform.d1.users',
      labId: 'd1-users',
      pattern: '/api/labs/d1-users',
      methods: ['GET', 'POST'],
      requestSchemas: { GET: 'none', POST: 'd1-user-create-v1' },
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'users'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 users laboratory API',
        description: 'Lists and creates visitor-scoped relational users in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['POST accepts JSON up to the shared readJson limit; GET consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.user',
      labId: 'd1-users',
      pattern: '/api/labs/d1-users/:id',
      methods: ['PATCH', 'DELETE'],
      requestSchemas: { PATCH: 'd1-user-update-v1', DELETE: 'none' },
      kind: 'api',
      handler: (request, env, params) => d1LabResponse(request, env, 'users', encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['PATCH', 'DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 user item laboratory API',
        description: 'Updates or deletes one visitor-scoped relational user in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['PATCH accepts JSON up to the shared readJson limit; DELETE consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.tasks',
      labId: 'd1-tasks',
      pattern: '/api/labs/d1-tasks',
      methods: ['GET', 'POST'],
      requestSchemas: { GET: 'none', POST: 'd1-task-create-v1' },
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'tasks'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 tasks laboratory API',
        description: 'Lists and creates visitor-scoped relational tasks in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['POST accepts JSON up to the shared readJson limit; GET consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.task',
      labId: 'd1-tasks',
      pattern: '/api/labs/d1-tasks/:id',
      methods: ['PATCH', 'DELETE'],
      requestSchemas: { PATCH: 'd1-task-update-v1', DELETE: 'none' },
      kind: 'api',
      handler: (request, env, params) => d1LabResponse(request, env, 'tasks', encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['PATCH', 'DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 task item laboratory API',
        description: 'Updates or deletes one visitor-scoped relational task in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        notes: ['PATCH accepts JSON up to the shared readJson limit; DELETE consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.reset',
      labId: 'd1-reset',
      pattern: '/api/labs/d1-reset',
      methods: ['POST'],
      requestSchemas: { POST: 'none' },
      kind: 'api',
      handler: (request, env) => d1LabResponse(request, env, 'reset'),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'D1 users and tasks reset laboratory API',
        description: 'Resets the visitor-scoped D1 users and tasks sandbox to deterministic seed rows.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the scoped sandbox without consuming a request body.'),
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.records',
      labId: 'rest-records',
      pattern: '/api/labs/rest-records',
      methods: ['GET', 'POST'],
      requestSchemas: { GET: 'none', POST: 'rest-record-create-v1' },
      kind: 'api',
      handler: (request, env) => recordsResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write POST' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'REST records laboratory API',
        description: 'Lists readable demo records or creates an authorized record in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['POST accepts JSON; record values are serialized to at most 4096 bytes.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.record',
      labId: 'rest-records',
      pattern: '/api/labs/rest-records/:id',
      methods: ['GET', 'PUT', 'DELETE'],
      requestSchemas: { GET: 'none', PUT: 'rest-record-replace-v1', DELETE: 'none' },
      kind: 'api',
      handler: (request, env, params) => recordsResponse(request, env, encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write PUT/DELETE' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'REST record item laboratory API',
        description: 'Reads, replaces, or deletes one authorized demo record in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['PUT accepts JSON; GET and DELETE consume no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.records-reset',
      labId: 'rest-records-reset',
      pattern: '/api/labs/rest-records-reset',
      methods: ['POST'],
      requestSchemas: { POST: 'none' },
      kind: 'api',
      handler: (request, env) => resetRecordSandboxResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:write visitor sandbox' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'REST record sandbox reset laboratory API',
        description: 'Deletes the authenticated visitor sandbox records from D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the authorized record namespace without consuming a request body.'),
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.rest-demo-records',
      labId: 'rest-demo-records',
      pattern: '/api/labs/rest-demo-records',
      methods: ['GET', 'POST'],
      requestSchemas: { GET: 'none', POST: 'rest-demo-record-create-v1' },
      kind: 'api',
      handler: (request, env) => restDemoResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'Anonymous REST demo collection API',
        description: 'Lists or creates visitor-scoped records for the OpenAPI interface demo without authentication.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['POST accepts JSON; records are isolated to an anonymous browser session.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
    {
      id: 'platform.d1.rest-demo-record',
      labId: 'rest-demo-records',
      pattern: '/api/labs/rest-demo-records/:id',
      methods: ['GET', 'PUT', 'PATCH', 'DELETE'],
      requestSchemas: { GET: 'none', PUT: 'rest-demo-record-write-v1', PATCH: 'rest-demo-record-write-v1', DELETE: 'none' },
      kind: 'api',
      handler: (request, env, params) => restDemoResponse(request, env, encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'Anonymous REST demo item API',
        description: 'Reads, replaces, partially updates, or deletes one visitor-scoped record without authentication.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/d1.ts',
        exportName: 'd1LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxValueBytes: 4_096,
        maxIdentifierCharacters: 64,
        notes: ['PUT and PATCH accept JSON; DELETE consumes no request body.'],
      },
      storage: D1_RELATIONAL_STORAGE,
    },
  ],
});
