import r2Demo from '../../demos/r2';
import {
  r2DemoObjectResponse,
  r2FilesResetResponse,
  r2FilesResponse,
  r2ObjectResponse,
} from '../../api/r2';
import { renderR2Demo } from '../../demos/r2-page';
import {
  R2_OBJECT_STORAGE,
  definePlatformLaboratoryCapability,
  noRequestBody,
} from '../route-capability';

const tests = [
  'tests/platform-laboratory-routing.test.ts',
  'tests/r2-lab.test.ts',
  'tests/router.test.ts',
] as const;

const docs = ['docs/ROUTES.md', 'docs/ROUTE-REGISTRY.md'] as const;

export const r2LaboratoryCapability = definePlatformLaboratoryCapability({
  id: 'platform.r2',
  routes: [
    {
      id: 'platform.r2.page',
      pattern: r2Demo.route,
      methods: ['GET'],
      kind: 'page',
      handler: (_request, env) => renderR2Demo(env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'allow' },
      documentation: { title: r2Demo.title, description: r2Demo.summary, docs },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('The R2 laboratory page accepts GET without a request body.'),
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.demo-object',
      pattern: '/__api/r2/demo',
      methods: ['POST'],
      kind: 'api',
      handler: (request, env) => r2DemoObjectResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 demonstration object API',
        description: 'Writes the deterministic public demonstration object to R2 with D1 metadata.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST writes a generated demonstration object and consumes no request body.'),
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.object',
      pattern: '/__api/r2/object',
      methods: ['GET', 'PUT', 'DELETE'],
      kind: 'api',
      handler: (request, env) => r2ObjectResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write PUT/DELETE' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 object API',
        description: 'Reads, stores, or deletes object bytes in R2 while D1 retains relational metadata.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxObjectBytes: 16_384,
        maxIdentifierCharacters: 80,
        notes: ['PUT accepts JSON up to the shared readJson limit; stored text content is capped at 16384 bytes.'],
      },
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.files',
      pattern: '/__api/r2/files',
      methods: ['GET', 'POST'],
      kind: 'api',
      handler: (request, env) => r2FilesResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 files laboratory API',
        description: 'Lists or uploads visitor-scoped files whose bytes live in R2 and metadata lives in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 5 * 1024 * 1024 + 65_536,
        maxObjectBytes: 5 * 1024 * 1024,
        maxObjectsPerSession: 10,
        maxTotalBytesPerSession: 20 * 1024 * 1024,
        notes: ['POST accepts multipart form data; the body allowance includes multipart overhead.'],
      },
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.file',
      pattern: '/__api/r2/files/:id',
      methods: ['GET', 'DELETE'],
      kind: 'api',
      handler: (request, env, params) => r2FilesResponse(request, env, encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 file item laboratory API',
        description: 'Streams a visible R2 object or deletes one owned by the visitor sandbox.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('GET and DELETE operate on the path identifier and do not consume a request body.'),
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.reset',
      pattern: '/__api/r2/reset',
      methods: ['POST'],
      kind: 'api',
      handler: (request, env) => r2FilesResetResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 files reset API',
        description: 'Deletes visitor-owned R2 objects and their D1 metadata rows.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the visitor R2 sandbox without consuming a request body.'),
      storage: R2_OBJECT_STORAGE,
    },
  ],
});
