import {
  r2DemoObjectResponse,
  r2FilesResetResponse,
  r2FilesResponse,
  r2ObjectResponse,
} from '../../api/r2';
import {
  R2_OBJECT_STORAGE,
  definePlatformLaboratoryCapability,
  noRequestBody,
} from '../route-capability';

const tests = [
  'tests/platform-laboratory-routing.test.ts',
  'tests/r2-lab.test.ts',
  'tests/router.test.ts',
] as const;

const docs = ['docs/ROUTES.md', 'docs/ROUTE-REGISTRY.md'] as const;

export const r2LaboratoryCapability = definePlatformLaboratoryCapability({
  id: 'platform.r2',
  routes: [

{
  id: 'platform.r2',
  pattern: '/platform/r2',
  methods: ['GET'],
  kind: 'page',
  handler: async (_request, env) => {
    const [{ r2Content }, { renderPage }] = await Promise.all([import('../../demos/r2-page'), import('../../ui/page')]);
    return renderPage(env, { ...r2Content(env), routeId: 'platform.r2' });
  },
  authentication: { mode: 'anonymous' }, authorization: { mode: 'none' }, visibility: 'public',
  sameOrigin: { mode: 'not-required' }, offline: { mode: 'gated' }, cache: { mode: 'no-store' },
  crawler: { crawling: 'controlled', indexing: 'allow' },
  documentation: { title: 'Cloudflare R2', description: 'Session-isolated file management backed by real R2 bytes and D1 metadata.', docs },
  source: { module: 'src/demos/r2-page.ts', exportName: 'r2Content', tests },
  requestLimits: noRequestBody('GET renders the R2 laboratory and consumes no request body.'), storage: R2_OBJECT_STORAGE,
  page: { parent: 'platform.index', label: 'R2', summary: 'Session-isolated file management backed by real R2 bytes and D1 metadata.', order: 4, navigation: 'secondary', architectureMap: true },
},
    {
      id: 'platform.r2.demo-object',
      labId: 'r2-demo',
      pattern: '/api/labs/r2-demo',
      methods: ['POST'],
      requestSchemas: { POST: 'none' },
      kind: 'api',
      handler: (request, env) => r2DemoObjectResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 demonstration object laboratory API',
        description: 'Writes the deterministic public demonstration object to R2 with D1 metadata.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST writes a generated demonstration object and consumes no request body.'),
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.object',
      labId: 'r2-objects',
      pattern: '/api/labs/r2-objects',
      methods: ['GET', 'PUT', 'DELETE'],
      requestSchemas: { GET: 'r2-object-key-query-v1', PUT: 'r2-object-put-v1', DELETE: 'r2-object-key-query-v1' },
      kind: 'api',
      handler: (request, env) => r2ObjectResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'policy', policy: 'demo:read GET; demo:write PUT/DELETE' },
      visibility: 'public',
      sameOrigin: { mode: 'not-required' },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 object laboratory API',
        description: 'Reads, stores, or deletes object bytes in R2 while D1 retains relational metadata.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 16_384,
        maxObjectBytes: 16_384,
        maxIdentifierCharacters: 80,
        notes: ['PUT accepts JSON up to the shared readJson limit; stored text content is capped at 16384 bytes.'],
      },
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.files',
      labId: 'r2-files',
      pattern: '/api/labs/r2-files',
      methods: ['GET', 'POST'],
      requestSchemas: { GET: 'none', POST: 'r2-file-upload-v1' },
      kind: 'api',
      handler: (request, env) => r2FilesResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 files laboratory API',
        description: 'Lists or uploads visitor-scoped files whose bytes live in R2 and metadata lives in D1.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: {
        maxBodyBytes: 5 * 1024 * 1024 + 65_536,
        maxObjectBytes: 5 * 1024 * 1024,
        maxObjectsPerSession: 10,
        maxTotalBytesPerSession: 20 * 1024 * 1024,
        notes: ['POST accepts multipart form data; the body allowance includes multipart overhead.'],
      },
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.file',
      labId: 'r2-files',
      pattern: '/api/labs/r2-files/:id',
      methods: ['GET', 'DELETE'],
      requestSchemas: { GET: 'r2-file-id-v1', DELETE: 'r2-file-id-v1' },
      kind: 'api',
      handler: (request, env, params) => r2FilesResponse(request, env, encodeURIComponent(params.id)),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['DELETE'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 file item laboratory API',
        description: 'Streams a visible R2 object or deletes one owned by the visitor sandbox.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('GET and DELETE operate on the path identifier and do not consume a request body.'),
      storage: R2_OBJECT_STORAGE,
    },
    {
      id: 'platform.r2.reset',
      labId: 'r2-reset',
      pattern: '/api/labs/r2-reset',
      methods: ['POST'],
      requestSchemas: { POST: 'none' },
      kind: 'api',
      handler: (request, env) => r2FilesResetResponse(request, env),
      authentication: { mode: 'anonymous' },
      authorization: { mode: 'none' },
      visibility: 'public',
      sameOrigin: { mode: 'required', methods: ['POST'] },
      offline: { mode: 'gated' },
      cache: { mode: 'no-store' },
      crawler: { crawling: 'controlled', indexing: 'deny' },
      documentation: {
        title: 'R2 files reset laboratory API',
        description: 'Deletes visitor-owned R2 objects and their D1 metadata rows.',
        docs,
      },
      source: {
        module: 'src/platform/route-capabilities/r2.ts',
        exportName: 'r2LaboratoryCapability',
        tests,
      },
      requestLimits: noRequestBody('POST resets the visitor R2 sandbox without consuming a request body.'),
      storage: R2_OBJECT_STORAGE,
    },
  ],
});
