import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const target = path.join(root, 'src', 'worker-entry.mjs');
const semanticVersion = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/;
const fullCommit = /^[0-9a-f]{40}$/;

function headCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  } catch {
    if (!process.env.WG_VERSION && !process.env.WG_COMMIT) return '0'.repeat(40);
    throw new Error('A release build requires a Git checkout');
  }
}

const version = process.env.WG_VERSION ?? '';
const commit = process.env.WG_COMMIT ?? '';
const head = headCommit();
let release: { version: string; commit: string };

if (!version && !commit) {
  release = { version: '0.0.0-dev', commit: fullCommit.test(head) ? head : '0'.repeat(40) };
} else {
  if (!version || !commit) throw new Error('WG_VERSION and WG_COMMIT must be set together');
  if (!semanticVersion.test(version)) throw new Error(`WG_VERSION must be X.Y.Z; received ${JSON.stringify(version)}`);
  if (!fullCommit.test(commit)) throw new Error('WG_COMMIT must be a full 40-character lowercase commit');
  if (commit !== head) throw new Error('WG_COMMIT must equal the checked-out commit');
  const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')) as { version?: string };
  if (pkg.version !== version) throw new Error(`WG_VERSION ${version} does not match package.json version ${String(pkg.version)}`);
  release = { version, commit };
}

mkdirSync(path.dirname(target), { recursive: true });
writeFileSync(target, [
  '// Generated by scripts/generate-worker-entry.ts. Do not edit.',
  release.version === '0.0.0-dev'
    ? "import { createLocalDemoWorker as createDemoWorker } from './local-worker.ts';"
    : "import { createDemoWorker } from './index.ts';",
  "export { DemoCoordinator } from './index.ts';",
  `export default createDemoWorker(${JSON.stringify(release)});`,
  '',
].join('\n'));

process.stdout.write(`Generated ${path.relative(root, target)} for ${release.version} at ${release.commit}.\n`);
