import {
  authorizationDecisionResponse,
  demoAccessTokenResponse,
  identityLogoutResponse,
  identitySessionResponse,
  providerCallbackResponse,
  providerStartResponse,
  samlCallbackResponse,
  samlMetadataResponse,
  samlStartResponse,
} from '../../api/identity';
import { defineInterfaceIdentityCapability, interfaceIdentityRoute } from '../route-capability';

const providers = ['microsoft', 'google', 'github'] as const;

const providerRoutes = providers.flatMap((provider) => [
  interfaceIdentityRoute({
    id: 'interfaces.identity.' + provider + '.start',
    pattern: '/auth/' + provider,
    methods: ['GET'],
    kind: 'protocol',
    handler: (request, { env }) => providerStartResponse(request, env, provider),
    title: provider + ' authorization start',
    description: 'Authorization-code flow start with state and PKCE; OIDC providers also bind a nonce.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'providerStartResponse',
    authorization: { mode: 'policy', policy: provider === 'github' ? 'oauth-state + PKCE' : 'oidc-state + nonce + PKCE' },
    tests: ['tests/identity.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.' + provider + '.callback',
    pattern: '/auth/' + provider + '/callback',
    methods: ['GET'],
    kind: 'protocol',
    handler: (request, { env }) => providerCallbackResponse(request, env, provider),
    title: provider + ' authorization callback',
    description: provider === 'github'
      ? 'OAuth callback validating state, PKCE-bound code exchange, and provider identity.'
      : 'OIDC callback validating state, nonce, PKCE, issuer, audience, signature, issued-at, and expiry.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'providerCallbackResponse',
    authorization: { mode: 'policy', policy: provider === 'github' ? 'oauth-state + PKCE + provider identity' : 'oidc-state + nonce + PKCE + issuer/audience/expiry' },
    tests: ['tests/identity.test.ts', 'tests/interface-consolidation.test.ts'],
  }),
]);

export const identityRouteCapability = defineInterfaceIdentityCapability('interfaces.identity', [
  interfaceIdentityRoute({
    id: 'interfaces.identity.authorize',
    pattern: '/auth/authorize',
    methods: ['POST'],
    kind: 'api',
    handler: (request, { env }) => authorizationDecisionResponse(request, env),
    title: 'Identity authorization decision',
    description: 'Same-origin session-backed demo authorization decision.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'authorizationDecisionResponse',
    authentication: { mode: 'required', provider: 'identity-session' },
    authorization: { mode: 'policy', policy: 'demo:read or demo:write' },
    visibility: 'private',
    sameOrigin: { mode: 'required', methods: ['POST'] },
    tests: ['tests/identity.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.token',
    pattern: '/auth/token',
    methods: ['POST'],
    kind: 'api',
    handler: (request, { env }) => demoAccessTokenResponse(request, env),
    title: 'Identity demo access token',
    description: 'Same-origin short-lived token issuance from a validated identity session.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'demoAccessTokenResponse',
    authentication: { mode: 'required', provider: 'identity-session' },
    authorization: { mode: 'policy', policy: 'identity-session token issuance' },
    visibility: 'private',
    sameOrigin: { mode: 'required', methods: ['POST'] },
    tests: ['tests/identity.test.ts'],
  }),
  ...providerRoutes,
  interfaceIdentityRoute({
    id: 'interfaces.identity.saml.start',
    pattern: '/auth/saml',
    methods: ['GET'],
    kind: 'protocol',
    handler: (request, { env }) => samlStartResponse(request, env),
    title: 'SAML sign-in start',
    description: 'SAML AuthnRequest creation with replay-bound flow state.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'samlStartResponse',
    authorization: { mode: 'policy', policy: 'SAML request state' },
    tests: ['tests/identity.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.saml.acs',
    pattern: '/auth/saml/acs',
    methods: ['POST'],
    kind: 'protocol',
    handler: (request, { env }) => samlCallbackResponse(request, env),
    title: 'SAML assertion consumer service',
    description: 'Cross-site IdP callback validating XML signature, issuer, audience, destination, time bounds, RelayState, and assertion replay.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'samlCallbackResponse',
    authorization: { mode: 'policy', policy: 'SAML signature + audience + time bounds + replay protection' },
    sameOrigin: { mode: 'not-required' },
    tests: ['tests/identity.test.ts', 'tests/interface-consolidation.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.saml.metadata',
    pattern: '/auth/saml/metadata',
    methods: ['GET'],
    kind: 'protocol',
    handler: (request) => samlMetadataResponse(request),
    title: 'SAML service-provider metadata',
    description: 'Public SAML service-provider metadata.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'samlMetadataResponse',
    cache: { mode: 'public', maxAgeSeconds: 300 },
    tests: ['tests/identity.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.session',
    pattern: '/auth/session',
    methods: ['GET'],
    kind: 'api',
    handler: (request, { env }) => identitySessionResponse(request, env),
    title: 'Identity session',
    description: 'Current disclosure-safe application identity session.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'identitySessionResponse',
    authorization: { mode: 'policy', policy: 'optional identity-session' },
    cache: { mode: 'private' },
    tests: ['tests/identity.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.identity.logout',
    pattern: '/auth/logout',
    methods: ['POST'],
    kind: 'api',
    handler: (request, { env }) => identityLogoutResponse(request, env),
    title: 'Identity logout',
    description: 'Same-origin identity-session invalidation.',
    sourceModule: 'src/api/identity.ts',
    sourceExport: 'identityLogoutResponse',
    authorization: { mode: 'policy', policy: 'optional identity-session invalidation' },
    sameOrigin: { mode: 'required', methods: ['POST'] },
    cache: { mode: 'private' },
    tests: ['tests/identity.test.ts'],
  }),
]);
