import {
  githubWebhookResponse,
  webhookDemoResponse,
  webhookEventsResponse,
  webhookReceiptResponse,
  webhookResetResponse,
} from '../../api/webhooks';
import { defineInterfaceIdentityCapability, interfaceIdentityRoute } from '../route-capability';

export const webhooksRouteCapability = defineInterfaceIdentityCapability('interfaces.webhooks', [
  interfaceIdentityRoute({
    id: 'interfaces.webhooks.demo-receipt',
    pattern: '/v1/webhooks/demo',
    methods: ['POST'],
    kind: 'protocol',
    handler: (request, { env }) => webhookReceiptResponse(request, env),
    title: 'Signed demo webhook receiver',
    description: 'HMAC-validated bounded webhook receiver with delivery replay protection.',
    sourceModule: 'src/api/webhooks.ts',
    sourceExport: 'webhookReceiptResponse',
    authorization: { mode: 'policy', policy: 'valid webhook HMAC and unique delivery ID' },
    tests: ['tests/webhooks.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.webhooks.github',
    pattern: '/v1/webhooks/github',
    methods: ['POST'],
    kind: 'protocol',
    handler: (request, { env }) => githubWebhookResponse(request, env),
    title: 'GitHub webhook receiver',
    description: 'GitHub-compatible receiver enforcing exact-body HMAC, repository/event allowlists, and replay protection.',
    sourceModule: 'src/api/webhooks.ts',
    sourceExport: 'githubWebhookResponse',
    authorization: { mode: 'policy', policy: 'github-hmac + repository/event allowlists + replay protection' },
    tests: ['tests/webhooks.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.webhooks.synthetic',
    pattern: '/__api/webhooks/demo',
    methods: ['POST'],
    kind: 'api',
    handler: (request, { env }) => webhookDemoResponse(request, env),
    title: 'Synthetic webhook action',
    description: 'Same-origin browser action that signs and exercises the production webhook validation path.',
    sourceModule: 'src/api/webhooks.ts',
    sourceExport: 'webhookDemoResponse',
    authorization: { mode: 'policy', policy: 'visitor-session' },
    sameOrigin: { mode: 'required', methods: ['POST'] },
    tests: ['tests/webhooks.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.webhooks.events',
    pattern: '/__api/webhooks/events',
    methods: ['GET'],
    kind: 'api',
    handler: (request, { env }) => webhookEventsResponse(request, env),
    title: 'Verified webhook events',
    description: 'Sanitized delivery evidence scoped to the current visitor session.',
    sourceModule: 'src/api/webhooks.ts',
    sourceExport: 'webhookEventsResponse',
    authorization: { mode: 'policy', policy: 'visitor-session' },
    tests: ['tests/webhooks.test.ts'],
  }),
  interfaceIdentityRoute({
    id: 'interfaces.webhooks.reset',
    pattern: '/__api/webhooks/reset',
    methods: ['POST'],
    kind: 'api',
    handler: (request, { env }) => webhookResetResponse(request, env),
    title: 'Webhook demo reset',
    description: 'Same-origin reset of synthetic webhook evidence for the current visitor session.',
    sourceModule: 'src/api/webhooks.ts',
    sourceExport: 'webhookResetResponse',
    authorization: { mode: 'policy', policy: 'visitor-session' },
    sameOrigin: { mode: 'required', methods: ['POST'] },
    tests: ['tests/webhooks.test.ts'],
  }),
]);
